<?php
/**
 * Created by kolserdav
 * User: Sergey Kol'miller
 * Date: 28.03.2018
 * Time: 9:46
 */

namespace Avir\Model;


class ModelOne extends Model
{
    public function send(string $query_name)
    {
       return parent::send($query_name); // TODO: Change the autogenerated stub
    }
}