#index :                                           #route name [optional]
      #path : /                                    #'path' : path of route
      #controller: IndexController::indexPublic    #'controller' : class and operation of route
#users :
      #path : /users/
      #controller : User\UserConroller::usersPublic #if your controller place in Controller\User\UserController
#user :
      #path : /user/{id}                            #use 'id' in UserController with $this->id
      #controller : User\UserController::userPublic
tests :
      path: /tests/
      controller: TestController::tests
      hash: #Require field and name
              route1 : file::module1 #Custom fields with special format
              route2 : file::module2
routejs :
      path: /routejs-data
      controller: TestController::route
test :
      path : /test/{id}
      controller : TestController::test
ajax :
      path : /ajax
      controller : TestController::ajax
aj :
      path : /aj
      controller : TestController::aj
